Overture version upgrade
anaplan-engineering/vdm-pretty-printer pull request #2
Opened 2022-02-21 15:46 UTC by donbex

2022-03-01 10:20 UTC, sifraser requested changes

2022-03-01 10:20 UTC, sifraser commented on Jenkinsfile
> +def BUILD_LABEL = "azuki.${UUID.randomUUID().toString()}"
Not azuki

2022-03-01 10:21 UTC, sifraser commented on build.gradle
> +    testImplementation group: 'junit', name: 'junit', version: '4.13.2'
we should change this to use `kotlin-test` while we are here

2022-03-01 10:22 UTC, sifraser commented
Should probably also add `.editorconfig`

2022-03-01 10:34 UTC, donbex commented on Jenkinsfile
> +def BUILD_LABEL = "azuki.${UUID.randomUUID().toString()}"
🤦

2022-03-01 11:13 UTC, donbex commented
> Should probably also add `.editorconfig`

I was planning to do all the re-formatting in a separate PR, but I can do it here if you prefer.

2022-03-01 11:15 UTC, donbex commented on src/test/kotlin/com/anaplan/engineering/vdmprettyprinter/VdmSlReparseTest.kt
>  import org.junit.runners.Parameterized
Looks like `kotlin-test` only provides assumption checks.

2022-03-14 09:35 UTC, sifraser approved these changes

2022-03-14 09:35 UTC, merged